#!/bin/bash

export DISPLAY_NAME="Caffe Stazione Simulation"
export WEB_HOST_NAME="mattriley.github.io"
export WEB_BASE_PATH=""
export INDEXGEN_OPTIONS="--fullySpecified --type esm --filename index.mjs"
export TEST_RUNNER="jest"

export COV_BRANCHES=0
export COV_LINES=0
export COV_FUNCTIONS=0
export COV_STATEMENTS=0
