#!/bin/bash

export PROJECT_NAME="Stazione Simulation"
export INDEXGEN_OPTIONS="--fullySpecified"
export ESLINT_PATHS=("$SRC")
export DIST_PROD="$GITHUB_PAGES_PATH"

export COV_BRANCHES=0
export COV_LINES=0
export COV_FUNCTIONS=0
export COV_STATEMENTS=0
