#!/bin/bash
  
. ./task-vars

README="README.md"

node \
--experimental-specifier-resolution=node \
--experimental-loader @node-loader/babel \
./tasks/lib/readme-file-generator.js > $README

npx doctoc --maxlevel 2 $README
